### PR TITLE
Add Falcon signature algorithm

### PR DESCRIPTION
**Pull request by manvari**
With the new signature API.

### CODE REVIEW

**Comment by christianpaquin** [comment]
@manvari, we're integrating the sig API into OQS. Once that goes in (I'll let you know), you can PR the OQS project directly.

**Comment by dstebila** [comment]
Hi Maxime, thanks for contributing this!  Like Christian said, we're not 100% done on the signature API and associated changes yet; we hope to have that finished this week, and then we're happy to merge this!

**Comment by manvari** [comment]
@dstebila You're welcome! Thanks.

Since @christianpaquin's branch features (a first version of) the new sig API, I figured I would directly base my work off of it. Once the sig API has fully been rolled out, I will submit a new PR to `nist-branch` on the base repo with modifications where appropriate.

**Comment by dstebila** [comment]
BTW, @manvari, I plan to do the next snapshot release of liboqs nist-branch on July 27 -- see the timeline at https://github.com/open-quantum-safe/liboqs/projects/8.  If you can have the Falcon PR in by say the 21st or 22nd, I should be able to include it, assuming there aren't significant issues in merging.

**Pull request closed without merging**
